# Generated by Django 4.2.6 on 2023-11-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='Unpaid', max_length=30),
            preserve_default=False,
        ),
    ]
