# Generated by Django 4.2.6 on 2023-11-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('detail', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
